// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMWkcDMj2qNjPkUqp9YOltSSOemAkGzQo',
    appId: '1:933945132412:web:af6e0d01c6857b3da910f9',
    messagingSenderId: '933945132412',
    projectId: 'eventa-db16a',
    authDomain: 'eventa-db16a.firebaseapp.com',
    storageBucket: 'eventa-db16a.firebasestorage.app',
    measurementId: 'G-4ZLYF26DLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ8c2lT5nzBYruF5j6gT-HRW7CO6m8UMA',
    appId: '1:933945132412:android:77e6ba167a40d9dea910f9',
    messagingSenderId: '933945132412',
    projectId: 'eventa-db16a',
    storageBucket: 'eventa-db16a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlYmwKf3u8uygYYi2HP9sbkzRnJibfYCc',
    appId: '1:933945132412:ios:3a41afee99794e74a910f9',
    messagingSenderId: '933945132412',
    projectId: 'eventa-db16a',
    storageBucket: 'eventa-db16a.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlYmwKf3u8uygYYi2HP9sbkzRnJibfYCc',
    appId: '1:933945132412:ios:3a41afee99794e74a910f9',
    messagingSenderId: '933945132412',
    projectId: 'eventa-db16a',
    storageBucket: 'eventa-db16a.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMWkcDMj2qNjPkUqp9YOltSSOemAkGzQo',
    appId: '1:933945132412:web:68974fd1863de84ca910f9',
    messagingSenderId: '933945132412',
    projectId: 'eventa-db16a',
    authDomain: 'eventa-db16a.firebaseapp.com',
    storageBucket: 'eventa-db16a.firebasestorage.app',
    measurementId: 'G-S5H5X4Q328',
  );
}
